potter_app/urls.py
from django.urls import path
from potter_app import views, back_views

app_name = 'pottersville_app'

urlpatterns = [
    path("album/", views.gallery, name="gallery"),
    path("dashboard/", back_views.dashboard, name="dashboard"),
    path('login/', back_views.login_view, name='login'),
   	path('register/', back_views.register, name='register'),
   	path('activate/<uidb64>/<token>/', back_views.activate, name='activate'),

   	path('add-category/', back_views.AddCategory.as_view(), name='add-category'),
   	path('view-category/', back_views.ListCategory.as_view(), name='view-category'),
   	path('update-category/<int:pk>',
   	     back_views.UpdateCategory.as_view(), name='update-category'),
   	path('delete-category/<int:pk>',
   	     back_views.DeleteCategory.as_view(), name='delete-category'),

    
    path('add-album/', back_views.AddGallery.as_view(), name='add-album'),
   	path('view-album/', back_views.ListGallery.as_view(), name='view-album'),
   	path('update-album/<int:pk>',
   	     back_views.UpdateGallery.as_view(), name='update-album'),
   	path('delete-album/<int:pk>',
   	     back_views.DeleteGallery.as_view(), name='delete-album'),

    
    path('add-event/', back_views.AddEvent.as_view(), name='add-event'),
   	path('view-events/', back_views.ListEvent.as_view(), name='view-events'),
   	path('update-event/<int:pk>',
   	     back_views.UpdateEvent.as_view(), name='update-event'),
   	path('delete-event/<int:pk>',
   	     back_views.DeleteEvent.as_view(), name='delete-event'),

    path("edit-profile/", back_views.edit_form, name="edit-profile"),
   	path("page-logout/", back_views.logout, name="page-logout"),











    # path("logout/", back_views.logout, name="logout"),
    # path("reset-password/", back_views.reset_password, name="reset-password"),
    # path("add-album/", back_views.add_album, name="add-album"),
    # path("view-album/", back_views.view_album, name="view-album"),
    # path("add-category/", back_views.add_category, name="add-category"),
    # path("view-category/", back_views.view_category, name="view-category"),
    # path("add-event/", back_views.add_event, name="add-event"),
    # path("view-events/", back_views.view_events, name="view-events"),

    
]

pottersville/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from potter_app import views, back_views

urlpatterns = [
    path('', views.index, name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('pottersville/', include('potter_app.urls')),
    path('admin/', admin.site.urls),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  

potter_app/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT)


class Category(models.Model):
    cat_name = models.CharField(verbose_name="Category Name", max_length=50)
    cat_desc = models.TextField(verbose_name="Category Description")

    def __str__(self):
        return self.cat_name

class Gallery(models.Model):
    name = models.CharField(max_length=50, default="")
    category = models.ForeignKey(Category,on_delete=models.CASCADE, default="")
    gallery_img = models.ImageField(verbose_name= "Image", upload_to='uploads/gallery', default="")
    date_created = models.DateTimeField(verbose_name="Date Created", default=timezone.now)

    def __str__(self):
        return self.name


class Events(models.Model):
    name = models.CharField(max_length=50)
    desc = models.TextField(verbose_name="Description")
    image = models.ImageField(upload_to='uploads/events')
    date_created = models.DateField(
        verbose_name="Date Created", default=timezone.now)
    time_created = models.TimeField(
        verbose_name="Time Created", default=timezone.now)

    def __str__(self):
        return self.name

potter_app/forms.py
# Importing forms in django


from django import forms
from potter_app.models import Category, Events

class RegisterForm(forms.Form):
	name = forms.CharField(label='Enter Your Name', required=True, widget=forms.TextInput(
		attrs={'class': 'form-group', 'placeholder': 'Your Name','type':'text',}))
	from_email = forms.EmailField(label="Enter Your Email", required=True, widget=forms.TextInput(
		attrs={'class': 'form-group', 'placeholder': 'Your Email', 'type': 'email'}))
	message = forms.CharField(label='Type Your Messages',required=True, widget=forms.Textarea(
		attrs={'class': 'form-group', 'placeholder': 'I would like to talk to...'}))

potter_app/views.py
from django.shortcuts import render
from potter_app.models import Category, Events, Gallery
from .forms import RegisterForm
from django.contrib import messages
from django.template.loader import get_template
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.core.mail import EmailMessage
from django.core.mail import send_mail
from django.conf import settings
# Create your views here.


def index(request):
    register_class = RegisterForm
    if request.method == 'POST':
        register = register_class(data=request.POST)
        if register.is_valid():
            name = request.POST.get('name', '')
            from_email = request.POST.get('from_email', '')
            message = request.POST.get('message', '')

            template = get_template('front/contact.html')
            context = {
                'name': name,
                'from_email': from_email,
                'message': message,
            }
            content = template.render(context)
            email = EmailMessage(
                "New Contact form Submission",
                content,
                "www.pottersville.com.ng" + '',
                ['pottersvilleprivateschool@gmail.com'],
                headers={'Reply-To': from_email}
            )
            email.send()
            messages.success(request, "EMAIL SENT SUCCESSFULLY")
            return redirect('index')
        else:
            messages.error(request, "INVALID FORM INPUT")
    show_event = Events.objects.all()

    index_dict = {
        'title': 'Pottersville Private School',
        'form': register_class,
        'event_list': show_event,

    }

    return render(request, 'front/index.html', context=index_dict)


def gallery(request):
    show_facilities = Gallery.objects.filter(category__cat_name="Facilities")
    show_music = Gallery.objects.filter(category__cat_name="Musicale")
    show_culture = Gallery.objects.filter(category__cat_name="Culture")
    show_sport = Gallery.objects.filter(category__cat_name="Sports")
    show_other = Gallery.objects.filter(category__cat_name="Others")
    category = Category.objects.all()




    register_class = RegisterForm
    if request.method == 'POST':
        register = register_class(data=request.POST)
        if register.is_valid():
            name = request.POST.get('name', '')
            from_email = request.POST.get('from_email', '')
            message = request.POST.get('message', '')

            template = get_template('front/contact.html')
            context = {
                'name': name,
                'from_email': from_email,
                'message': message,
            }
            content = template.render(context)
            email = EmailMessage(
                "New Contact form Submission",
                content,
                "www.pottersville.com.ng" + '',
                ['pottersvilleprivateschool@gmail.com'],
                headers={'Reply-To': from_email}
            )
            email.send()
            messages.success(request, "EMAIL SENT SUCCESSFULLY")
            return redirect('index')
        else:
            messages.error(request, "INVALID FORM INPUT")

    gallery_dict = {
        'title': 'Pottersville Private School',
        'form': register_class,
        'facilities_list': show_facilities,
        'music_list': show_music,
        'culture_list': show_culture,
        'sport_list': show_sport,
        'other_list': show_other,
        'category': category,

    }
    return render(request, 'front/gallery.html', context=gallery_dict)

templates/back/add-album.html
{% extends 'back/base.html' %}
{% load static %}
{% block title %}
Add Album | Pottersville Admin
{% endblock title %}

{% block main %}
{% include 'back/wrapper-navbar.html' %}
<!-- MAIN -->
		<div class="main">
			<!-- MAIN CONTENT -->
			<div class="main-content">
				<div class="container-fluid">
					<!-- OVERVIEW -->
					<div class="panel panel-headline">
						<div class="panel-heading">
							<h3 class="panel-title">
							{% if not form.instance.pk %}
								Add Album
								{% else %}
								Edit Album
							{% endif %}</h3>
						</div>
						<div class="panel-body">
							<div class="row">
								<form class="form-auth-small" method="post" enctype="multipart/form-data">
									{% csrf_token %}
									{% for field in form %}
										<div class="form-group">
											<label>{{ field.label_tag }}</label>
											<span> {{ field }}</span>
											{% if field.help_text %}
												<small style="color: grey">{{ field.help_text }}</small>
											{% endif %}
											{% for error in field.errors %}
												<p style="color: red">{{ error }}</p>
											{% endfor %}
										</div>
									{% endfor %}
									{% if not form.instance.pk %}
									<button class="btn btn-primary btn-block">
										Add Album
									</button>
									{% else %}
									<button class="btn btn-primary btn-block">
										Edit Album
									</button>
									{% endif %}

									
								</form>
								
							</div>
							
						</div>
					</div>
					<!-- END OVERVIEW -->
					
				</div>
			</div>
			<!-- END MAIN CONTENT -->
		</div>
		<!-- END MAIN -->
{% endblock main %}

templates/back/email_verification.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,

http://{{domain }}{% url 'pottersville_app:activate' uidb64=uid token=token %}
{% endautoescape %}
	             





              

templates/back/page-login.html
{% extends 'back/base.html' %}
{% load static %}
{% block title %}
Login | Pottersville Admin
{% endblock title %}
{% block main %}
    <div class="vertical-align-wrap">
        <div class="vertical-align-middle">
            <div class="auth-box ">
                <div class="left">
                    <div class="content">
                        <div class="header">
                            <div class="logo text-center"><img src="{% static 'back/assets/img/logo-dark.png' %}" alt="Klorofil Logo"></div>
                            <p class="lead">Login to your account</p>
                        </div>
                        <form class="form-auth-small" method="POST" action="{% url 'pottersville_app:login' %}">
                            {{ form.as_p }}
                            {% csrf_token %}
                            <div class="form-group clearfix">
                                <label class="fancy-checkbox element-left">
                                    <input type="checkbox">
                                    <span>Remember me</span>
                                </label>
                            </div>
                            <button type="submit" class="btn btn-primary btn-md btn-block">LOGIN</button>
                            <div class="bottom">
                                <span class="helper-text"><i class="fa fa-lock"></i> <a href="{% url 'password_reset' %}">Forgot password?</a></span>
                            </div>
                            
                        </form>
                        <!--<div class="bottom">-->
                        <!--        <a href="{% url 'pottersville_app:register'%}" style="color:#FEC400;">Register</a>-->
                        <!--</div> -->
                        
                    </div>
                </div>
                <div class="right">
                    <div class="overlay"></div>
                    <div class="content text">
                        <h1 class="heading">Pottersville Private School</h1>
                        <p>Admin</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock main %}

templates/back/page-logout.html
{% extends 'back/base.html' %}
{% load static %}
{% block title %}
Logout | Pottersville Admin
{% endblock title %}
{% block main %}

<div class="vertical-align-wrap">
	<div class="vertical-align-middle">
		<div class="auth-box">
			<div class="content">
				<div class="header text-center">
					<div class="logo text-center"><img src="{% static 'back/assets/img/logo-dark.png' %}" alt="Klorofil Logo"></div>
					<p class="lead">Are you sure you want to logout?</p>
					<a href="{% url 'logout' %}" class="btn btn-primary">Yes</a>
					<a href="{% url 'pottersville_app:dashboard' %}" class="btn btn-danger">No</a>
				</div>
				
				
			</div>
		</div>
	</div>
</div>

{% endblock main %}

templates/back/page-register.html
{% extends 'back/base.html' %}
{% load static %}
{% block title %}
Register | Pottersville Admin
{% endblock title %}
{% block main %}
    <div class="vertical-align-wrap">
        <div class="vertical-align-middle">
            <div class="auth-box ">
                <div class="left">
                    <div class="content">
                        <div class="header">
                            {% comment %} <div class="logo text-center"><img src="{% static 'back/assets/img/logo-dark.png' %}" alt="Klorofil Logo"></div> {% endcomment %}
                            <h4 style="color:#FEC400;">Register</h4>
                        </div>
                        <form class="form-auth-small" method="POST" class="form">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                    <span> {{ field }}</span>
                                    {% if field.help_text %}
                                    <small style="color: grey">{{ field.help_text }}</small>
                                    {% endif %}
                                    {% for error in field.errors %}
                                    <p style="color: red">{{ error }}</p>
                                    {% endfor %}
                                </div>
                            {% endfor %}
                            <button type="submit" class="btn btn-primary btn-md btn-block">REGISTER</button>
                        </form>
                        <div class="bottom">
                            <a href="{% url 'pottersville_app:login'%}">Login</a>
                        </div>
                        <div class="bottom">
                            <span class="helper-text"><i class="fa fa-lock"></i> <a href="{% url 'password_reset' %}">Forgot password?</a></span>
                        </div>
                    </div>
                </div>
                <div class="right">
                    <div class="overlay"></div>
                    <div class="content text">
                        <h1 class="heading">Pottersville Private School</h1>
                        <p>Admin</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock main %}

templates/back/view-album.html
{% extends 'back/base.html' %}
{% load static %}
{% block title %}
View Album | Pottersville Admin
{% endblock title %}

{% block main %}
{% include 'back/wrapper-navbar.html' %}

<!-- MAIN -->
<div class="main">
    <!-- MAIN CONTENT -->
    <div class="main-content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-headline">
                        <div class="panel-heading">
                            <h3 class="panel-title">View Album</h3>
                            <div class="right">
                                <button type="button" class="btn-toggle-collapse"><i class="lnr lnr-chevron-up"></i></button>
                                <button type="button" class="btn-remove"><i class="lnr lnr-cross"></i></button>
                            </div>
                        </div>
                        <div class="panel-body no-padding">
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert alert-success">{{ message }}</div>
                                {% endfor %}
                            {% endif %}
                            <table class="table table-striped" id="table_search">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Category</th>
                                        <th>Image</th>
                                        <th>Date Created</th>
                                        <th class="text-center">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% if view_album %}
                                    {% for album in view_album %}
                                        <tr>
                                            <td>{{album.name}}</td>
                                            <td>{{album.category}}</td>
                                            <td><img style="width:40px;" src="{{album.gallery_img.url}}"></img></td>
                                            <td>{{album.date_created}}</td>
                                            <td><a href="{% url 'pottersville_app:update-album' album.id %}">
                                                <button type="button" class="btn btn-success btn-sm">
                                                    <i class="fa fa-pencil-square-o"></i>
                                                </button></a>
                                            </td>
                                            <td>
                                                <form action="{% url 'pottersville_app:delete-album' album.id %}" method="post">{% csrf_token %}
                                                    <button type="submit" class="btn btn-danger btn-sm">
                                                        <i class="fa fa-trash"></i>
                                                    </button>
                                                </form>
                                            </form>
                                            </td>

                                        </tr>
                                    {% endfor %}
                                {% endif %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <!-- END RECENT PURCHASES -->
                </div>
            </div>
            
        </div>
    </div>
    <!-- END MAIN CONTENT -->
</div>
<!-- END MAIN -->
{% endblock main %}

templates/back/view-category.html
{% extends 'back/base.html' %}
{% load static %}
{% block title %}
View Category | Pottersville Admin
{% endblock title %}

{% block main %}
{% include 'back/wrapper-navbar.html' %}

<!-- MAIN -->
<div class="main">
<!-- MAIN CONTENT -->
<div class="main-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-headline">
                    <div class="panel-heading">
                        <h3 class="panel-title">View Category</h3>
                        <div class="right">
                            <button type="button" class="btn-toggle-collapse"><i class="lnr lnr-chevron-up"></i></button>
                            <button type="button" class="btn-remove"><i class="lnr lnr-cross"></i></button>
                        </div>
                    </div>
                    <div class="panel-body no-padding">
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert alert-success">{{ message }}</div>
                                {% endfor %}
                            {% endif %}
                        <table class="table table-striped" id="table_search">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Description</th>
                                    <th class="text-center">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% if view_cat %}
                                {% for cat in view_cat %}
                                    <tr>
                                        <td>{{cat.cat_name}}</td>
                                        <td>{{cat.cat_desc}}</td>
                                        <td><a href="{% url 'pottersville_app:update-category' cat.id %}">
                                            <button type="button" class="btn btn-success btn-sm">
                                                <i class="fa fa-pencil-square-o"></i>
                                            </button></a>
                                        </td>
                                        <td><form action="{% url 'pottersville_app:delete-category' cat.id %}" method="post">{% csrf_token %}
                                                <button type="submit" class="btn btn-danger btn-sm">
                                                    <i class="fa fa-trash"></i>
                                                </button>
                                            </form>
                                        </td>

                                    </tr>
                                {% endfor %}
                            {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- END RECENT PURCHASES -->
            </div>
        </div>
        
    </div>
</div>
<!-- END MAIN CONTENT -->
</div>
<!-- END MAIN -->
{% endblock main %}

templates/back/view-events.html
{% extends 'back/base.html' %}
{% load static %}
{% block title %}
View Events | Pottersville Admin
{% endblock title %}

{% block main %}
{% include 'back/wrapper-navbar.html' %}

<!-- MAIN -->
<div class="main">
    <!-- MAIN CONTENT -->
    <div class="main-content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-headline">
                        <div class="panel-heading">
                            <h3 class="panel-title">View Events</h3>
                            <div class="right">
                                <button type="button" class="btn-toggle-collapse"><i class="lnr lnr-chevron-up"></i></button>
                                <button type="button" class="btn-remove"><i class="lnr lnr-cross"></i></button>
                            </div>
                        </div>
                        <div class="panel-body no-padding">
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert alert-success">{{ message }}</div>
                                {% endfor %}
                            {% endif %}
                            <table class="table table-striped" id="table_search">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Description</th>
                                        <th>Image</th>
                                        <th>Date of Event</th>
                                        <th>Time of Event</th>
                                        <th class="text-center">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% if view_events %}
                                    {% for event in view_events %}
                                        <tr>
                                            <td style="width:20%;">{{event.name}}</td>
                                            <td style="width:20%;">{{event.desc}}</td>
                                            <td><img style="width:100px;" src="{{event.image.url}}"></td>
                                            <td>{{event.date_created}}</td>
                                            <td>{{event.time_created}}</td>
                                            <td><a href="{% url 'pottersville_app:update-event' event.id %}">
                                                <button type="submit" class="btn btn-success btn-sm">
                                                    <i class="fa fa-pencil-square-o"></i>
                                                </button></a>
                                            </td>
                                            <td>
                                                <form action="{% url 'pottersville_app:delete-event' event.id %}" method="post">{% csrf_token %}
                                                    <button type="submit" class="btn btn-danger btn-sm">
                                                        <i class="fa fa-trash"></i>
                                                    </button>
                                                </form>
                                            </td>

                                        </tr>
                                    {% endfor %}
                                {% endif %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <!-- END RECENT PURCHASES -->
                </div>
            </div>
            
        </div>
    </div>
    <!-- END MAIN CONTENT -->
</div>
<!-- END MAIN -->
{% endblock main %}

templates/back/wrapper-navbar.html
{% load static %}

<!-- NAVBAR -->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="brand">
        <a href="index.html"><img src="{% static 'back/assets/img/logo-dark.png' %}" alt="Klorofil Logo" class="img-responsive logo"></a>
    </div>
    <div class="container-fluid">
        <div class="navbar-btn">
            <button type="button" class="btn-toggle-fullwidth"><i class="lnr lnr-arrow-left-circle"></i></button>
        </div>
        <form class="navbar-form navbar-left">
            <div class="input-group">
                <input type="text" id="search" class="form-control" placeholder="Search dashboard...">
                <span class="input-group-btn"><button type="button" class="btn btn-primary">Go</button></span>
            </div>
        </form>
        <div id="navbar-menu">
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="{% static 'back/assets/img/user.png' %}" class="img-circle" alt="Avatar"> <span>{{user.username}}</span> <i class="icon-submenu lnr lnr-chevron-down"></i></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'pottersville_app:edit-profile' %}"><i class="lnr lnr-user"></i> <span>Edit Profile</span></a></li>
                        <li><a href="{% url 'password_reset' %}"><i class="fa fa-key"></i> <span>Reset Password</span></a></li>
                        <li><a href="{% url 'pottersville_app:page-logout' %}"><i class="lnr lnr-exit"></i> <span>Logout</span></a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- END NAVBAR -->
<!-- LEFT SIDEBAR -->
<div id="sidebar-nav" class="sidebar">
    <div class="sidebar-scroll">
        <nav>
            <ul class="nav">
                <li><a href="{% url 'pottersville_app:dashboard' %}" class="active"><i class="lnr lnr-home"></i> <span>Dashboard</span></a></li>
                <li>
                    <a href="#category" data-toggle="collapse" class="collapsed"><i class="fa fa-object-group"></i> <span>Category</span> <i class="icon-submenu lnr lnr-chevron-left"></i></a>
                    <div id="category" class="collapse ">
                        <ul class="nav">
                            <li><a href="{% url 'pottersville_app:view-category' %}" class="">View Category</a></li>
                            <li><a href="{% url 'pottersville_app:add-category' %}" class="">Add Category</a></li>
                        </ul>
                    </div>
                </li>
                <li>
                    <a href="#album" data-toggle="collapse" class="collapsed"><i class="fa fa-file-image-o"></i> <span>Album</span> <i class="icon-submenu lnr lnr-chevron-left"></i></a>
                    <div id="album" class="collapse ">
                        <ul class="nav">
                            <li><a href="{% url 'pottersville_app:view-album' %}" class="">View Album</a></li>
                            <li><a href="{% url 'pottersville_app:add-album' %}" class="">Add Album</a></li>
                        </ul>
                    </div>
                </li>
                <li>
                    <a href="#event" data-toggle="collapse" class="collapsed"><i class="fa fa-calendar-o"></i> <span>Events</span> <i class="icon-submenu lnr lnr-chevron-left"></i></a>
                    <div id="event" class="collapse ">
                        <ul class="nav">
                            <li><a href="{% url 'pottersville_app:view-events' %}" class="">View Events</a></li>
                            <li><a href="{% url 'pottersville_app:add-event' %}" class="">Add Event</a></li>
                        </ul>
                    </div>
                </li>
                <li><a href="{% url 'pottersville_app:page-logout' %}" class=""><i class="lnr lnr-exit"></i> <span>Logout</span></a></li>
            </ul>
        </nav>
    </div>
</div>

templates/front/contact.html
{% autoescape off %}
Name: {{ name }},
Email: {{from_email}}
Message: {{message}}
{% endautoescape %}